FROM node:10-alpine3.9

WORKDIR /app

COPY package.json ./

RUN npm install --only=prod

RUN npm install pm2 -g

ARG PORT
# database environment variables
ARG MYSQL_HOST
ARG MYSQL_USER
ARG MYSQL_PASSWORD
ARG MYSQL_DATABASE
ARG MHFR_SMTP_HOST
ARG MHFR_SMTP_PORT
ARG MHFR_SMTP_USER
ARG MHFR_SMTP_USER_PASSWORD

# email worker env variables
ARG MHFR_EMAIL_USER
ARG MHFR_EMAIL_PASSWORD
ARG MHFR_FACILITIES_PATH
ARG MHFR_EMAIL_WORKER_CRON_EXPR
ARG MHFR_MEDICAL_COUNCIL_EMAIL

ENV PORT=${PORT}
# database environment variables
ENV MYSQL_HOST=${MYSQL_HOST}
ENV MYSQL_USER=${MYSQL_USER}
ENV MYSQL_PASSWORD=${MYSQL_PASSWORD}
ENV MYSQL_DATABASE=${MYSQL_DATABASE}

ENV MHFR_SMTP_HOST=${MHFR_SMTP_HOST}
ENV MHFR_SMTP_PORT=${MHFR_SMTP_PORT}
ENV MHFR_SMTP_USER=${MHFR_SMTP_USER}
ENV MHFR_SMTP_USER_PASSWORD=${MHFR_SMTP_USER_PASSWORD}

# email worker env variables
ENV MHFR_EMAIL_USER=${MHFR_EMAIL_USER}
ENV MHFR_EMAIL_PASSWORD=${MHFR_EMAIL_PASSWORD}
ENV MHFR_FACILITIES_PATH=${MHFR_FACILITIES_PATH}
ENV MHFR_EMAIL_WORKER_CRON_EXPR=${MHFR_EMAIL_WORKER_CRON_EXPR}
ENV MHFR_MEDICAL_COUNCIL_EMAIL=${MHFR_MEDICAL_COUNCIL_EMAIL}

COPY . .

CMD [ "pm2-runtime", "server/server.js" ]
